SELECT
  CUSTOMER_ID,
  INITCAP(FIRST_NAME) AS FIRST_NAME,
  INITCAP(LAST_NAME) AS LAST_NAME,
  LOWER(EMAIL) AS EMAIL,
  REGEXP_REPLACE(PHONE, '[^0-9]', '') AS PHONE_CLEANED,
  DOB,
  ACCOUNT_OPEN_DATE,
  TRIM(UPPER(ACCOUNT_STATUS)) AS ACCOUNT_STATUS,
  LAST_UPDATED
FROM {{ source('public', 'STG_CUSTOMERS') }}
WHERE
  CUSTOMER_ID IS NOT NULL
  AND FIRST_NAME IS NOT NULL
  AND LAST_NAME IS NOT NULL
  AND EMAIL IS NOT NULL
  AND DOB IS NOT NULL
  AND LENGTH(REGEXP_REPLACE(PHONE, '[^0-9]', '')) BETWEEN 10 AND 12
  AND TRIM(UPPER(ACCOUNT_STATUS)) IN ('ACTIVE', 'INACTIVE')