SELECT
  ACCOUNT_ID,
  CUSTOMER_ID,
  TRIM(UPPER(ACCOUNT_TYPE)) AS ACCOUNT_TYPE,
  ROUND(BALANCE, 2) AS BALANCE,
  LAST_TRANSACTION_DATE,
  TRIM(UPPER(ACCOUNT_STATUS)) AS ACCOUNT_STATUS,
  LAST_UPDATED
FROM {{ source('public', 'STG_ACCOUNTS') }}
WHERE
  ACCOUNT_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND TRIM(UPPER(ACCOUNT_TYPE)) IN ('CHECKING', 'SAVINGS')
  AND BALANCE >= 0
  AND LAST_TRANSACTION_DATE IS NOT NULL
  AND TRIM(UPPER(ACCOUNT_STATUS)) IN ('ACTIVE', 'INACTIVE')