SELECT
  TRANSACTION_ID,
  CUSTOMER_ID,
  TRANSACTION_DATE,
  AMOUNT,
  MERCHANT,
  CATEGORY,
  TRANSACTION_TYPE,
  TRIM(UPPER(TRANSACTION_STATUS)) AS TRANSACTION_STATUS,
  LAST_UPDATED
FROM {{ source('public', 'STG_TRANSACTIONS') }}
WHERE
  TRANSACTION_ID IS NOT NULL
  AND CUSTOMER_ID IS NOT NULL
  AND AMOUNT >= 0
  AND TRIM(UPPER(TRANSACTION_STATUS)) IN ('COMPLETED', 'FAILED')
